spring.application.name=blog
app.frontend.url=http://localhost:4200/
api.security.token.secret=${JWT_SECRET:7d656098-8e6f-4c33-8a3d-495276e07a61}
logging.level.br.com.jeffsdac.blog=INFO
logging.level.br.com.jeffsdac.blog.blog.config.RequestLoggingFilter=DEBUG
logging.level.br.com.jeffsdac.blog.blog.config.AuthenticationFilter=DEBUG
